# Generated by Django 5.2 on 2025-04-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctorsmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('age', models.PositiveIntegerField()),
                ('specialization', models.CharField(choices=[('Cardiology', 'Cardiology'), ('Neurology', 'Neurology'), ('Pediatrics', 'Pediatrics'), ('Dermatology', 'Dermatology'), ('Orthopedics', 'Orthopedics'), ('General', 'General')], max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('licence_number', models.CharField(max_length=50, unique=True)),
                ('available_time_from', models.TimeField()),
                ('available_time_to', models.TimeField()),
                ('date_joined', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
